name: Release build

on:
  push:
    branches:
      - develop
    # tags:
    #   - v*

jobs:
  release:
    name: Build runners distribution
    runs-on: ubuntu-latest
    container: node:12
    strategy:
      matrix: 
        lambda: ["modules/webhook/lambdas/webhook", "modules/runner-binaries-syncer/lambdas/runner-binaries-syncer", "modules/runners/lambdas/runners"]
    env:
      lambda_webhook_name: webhook
      lambda_runners_name: runners
      lambda_syncer_name: runner-binaries-syncer
    steps:
      - name: Extract lambda name
        id: lambda
        env:
          LAMBDA: ${{ matrix.lambda }}
        run: echo ::set-output name=name::${LAMBDA##*/}
      - uses: actions/checkout@v2
      - name: Add zip
        run: apt update && apt install zip
      - name: Lambda webhook - build
        working-directory: ${{ matrix.lambda }}
        run: yarn install && yarn run test && yarn dist

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.lambda.outputs.name }}
          path: '**/*.zip'
          retention-days: 1

  release2:
    runs-on: ubuntu-latest
    # container: node:12
    # strategy:
    #   matrix: 
    #     lambda: ["modules/webhook/lambdas/webhook", "modules/runner-binaries-syncer/lambdas/runner-binaries-syncer", "modules/runners/lambdas/runners"]

    needs:
      release
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: webhook
          path: artifacts
      - uses: actions/download-artifact@v2
        with:
          name: runners
          path: artifacts
      - uses: actions/download-artifact@v2
        with:
          name: runner-binaries-syncer
          path: artifacts

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: artifacts

      # - name: Lambda syncer - build
      #   working-directory: modules/runner-binaries-syncer/lambdas/runner-binaries-syncer
      #   run: yarn install && yarn dist
      # - name: Lambda syncer - Upload asset
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: modules/${{ env.lambda_syncer_name }}/lambdas/${{ env.lambda_syncer_name }}/${{ env.lambda_syncer_name }}.zip
      #     asset_name: ${{ env.lambda_syncer_name }}-${{ steps.tag_name.outputs.TAG }}.zip
      #     asset_content_type: application/zip

      # - name: Lambda runners - build
      #   env:
      #     lambda_path: modules/runners/lambdas/runners
      #   working-directory: modules/runners/lambdas/runners
      #   run: yarn install && yarn dist
      # - name: Lambda runners - Upload asset
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: modules/${{ env.lambda_runners_name }}/lambdas/${{ env.lambda_runners_name }}/${{ env.lambda_runners_name }}.zip
      #     asset_name: ${{ env.lambda_runners_name }}-${{ steps.tag_name.outputs.TAG }}.zip
      #     asset_content_type: application/zip
