name: "Terraform checks"
on:
  push:
    branches:
      - main
      - npalm/*
  pull_request:
    paths: ["**/*.tf", "**/*.hcl", "modules/**/*", ".github/workflows/terraform.yml", ".utils/**"]

permissions:
  contents: read
  pull-requests: write

jobs:

  verify:
    uses: ./.github/workflows/terraform-validate-template.yml
    name: Verify module for Terraform ${{ matrix.checks.terraform }} ${{ matrix.checks.continue-on-error == true && 'ignore errors' || '' }}
    with:
      terraform_version: ${{ matrix.checks.terraform }}
      suggestions: ${{ matrix.checks.suggestions }}
      continue-on-error: ${{ matrix.checks.continue-on-error }}
    strategy:
      fail-fast: false
      matrix:
        checks: [
          { terraform: "1.5", continue-on-error: false, suggestions: true },
          { terraform: "latest", continue-on-error: true, suggestions: false }
        ]
