name: "Terraform checks"
on:
  push:
    branches:
      - main
      - npalm/*
  pull_request:
    paths: ["**/*.tf", "**/*.hcl", "modules/**/*", ".github/workflows/terraform.yml", ".utils/**"]

permissions:
  contents: read
  pull-requests: write

jobs:

  verify:
    uses: ./.github/workflows/terraform-validate-template.yml
    name: Verify module for Terraform ${{ matrix.terraform }}
    with:
      terraform_version: ${{ matrix.terraform }}
      suggestions: ${{ matrix.terraform == '1.5' }}
      continue-on-error: ${{ matrix.terraform == '1.5' }}
    strategy:
      fail-fast: false
      matrix:
        terraform: ["1.5", "latest"]
